import { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import AdminLayout from '../components/admin/AdminLayout';
import PageHeader from '../components/PageHeader';
import { supabase } from '../lib/supabase';

export default function AdminPracticalEditor() {
  const { id } = useParams(); const navigate = useNavigate(); const [form, setForm] = useState({ practical_number: '', title: '', description: '', category: '', difficulty: 'Medium', duration_minutes: 45, is_active: true }); const [status, setStatus] = useState('');
  useEffect(() => { if (id === 'new' || !supabase) return; supabase.from('practicals').select('*').eq('id', id).single().then(({ data }) => data && setForm(data)); }, [id]);
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const save = async (event) => { event.preventDefault(); setStatus('Saving...'); const result = id === 'new' ? await supabase.from('practicals').insert(form) : await supabase.from('practicals').update(form).eq('id', id); setStatus(result.error ? 'Unable to save practical.' : 'Practical saved successfully.'); if (!result.error) setTimeout(() => navigate('/admin/practicals'), 500); };
  return <AdminLayout><PageHeader title={id === 'new' ? 'Add Practical' : 'Edit Practical'} subtitle="Manage practical content and publishing status" badge="Practical Editor" /><form className="admin-panel admin-editor" onSubmit={save}><div className="form-grid"><div className="field"><label>Practical Number</label><input type="number" value={form.practical_number} onChange={(event) => update('practical_number', Number(event.target.value))} required /></div><div className="field"><label>Title</label><input value={form.title} onChange={(event) => update('title', event.target.value)} required /></div><div className="field"><label>Category</label><input value={form.category || ''} onChange={(event) => update('category', event.target.value)} /></div><div className="field"><label>Difficulty</label><select value={form.difficulty || 'Medium'} onChange={(event) => update('difficulty', event.target.value)}><option>Easy</option><option>Medium</option><option>Advanced</option></select></div><div className="field"><label>Duration (minutes)</label><input type="number" value={form.duration_minutes || ''} onChange={(event) => update('duration_minutes', Number(event.target.value))} /></div><div className="field"><label>Status</label><select value={form.is_active ? 'active' : 'inactive'} onChange={(event) => update('is_active', event.target.value === 'active')}><option value="active">Active</option><option value="inactive">Inactive</option></select></div></div><div className="field" style={{ marginTop: 16 }}><label>Description</label><textarea rows="5" value={form.description || ''} onChange={(event) => update('description', event.target.value)} required /></div>{status && <div className={status.includes('Unable') ? 'inline-error' : 'inline-success'}>{status}</div>}<div className="action-row"><button className="action-btn primary" type="submit">Save Practical</button><button className="action-btn secondary" type="button" onClick={() => navigate('/admin/practicals')}>Cancel</button></div></form></AdminLayout>;
}
